- pyfarm/jobtypes/core/jobtype.py
It is a UUID now, converting to int will fail.
> Do not convert agent_id to int in JobType.node()

- pyfarm/agent/sysinfo/system.py
If a problem like this persists, it will clog up the temp directory.
> Log a warning when a tempfile could not be deleted

- pyfarm/agent/sysinfo/system.py
This is a follow-on to #188 that ensures `filesystem_is_case_sensitive` and `environment_is_case_sensitive` do not modify the file system or environment more often than they need to.
> sysinfo.system Improvements

- pyfarm/agent/etc/agent.yml
- tests/test_agent/test_http_core_client.py
Many of our recent test failure are because `http[s]://httpbin.org` has been down or slow to respond, especially over SSL.  This change changes the url we're testing against to point at one of pyfarm's web servers instead.
> Replace httpbin in tests

- pyfarm/jobtypes/core/internals.py
This fixes a bug which would leave the agent in an usable state if it
could not reach the master when trying to download a jobtype file.
> Accept args in lambda for jobtype download errback

- tests/test_agent/test_service.py
The broken nature of thhis test has never surfaced until now, because
the Travis instances don't have GPUs or cannot list them with lspci.
> Fix test when the test machine actually has a GPU

- docs/source/includes/commands/pyfarm-agent.out
- docs/source/includes/commands/pyfarm-agent_start.out
Reran the documentation generator against the latest master.  No major changes here except the removal of --systemid* from the docs and the addition of --run-control-file.
> Documentation Update

- pyfarm/agent/logger/python.py
- pyfarm/agent/testutil.py
Currently the config logger is very noisy during the tests making it difficult to quickly find issues.  This change fixes that issue by implementing `.disabled` on our logger class (which we were using but it didn't in fact do anything).
For a comparison, here's [before](https://s3.amazonaws.com/archive.travis-ci.org/jobs/49269512/log.txt) and here's [after](https://s3.amazonaws.com/archive.travis-ci.org/jobs/49270476/log.txt) this change.  Now the only config changes that are logged are those that take place within the test itself.
> Silence Configuration Logging during setUp()

- pyfarm/jobtypes/core/internals.py
This should fix the assertion error in #209.  The problem is caused by `self._tempdirs` being a set object originally.
> Fix type check in _remove_directories

- pyfarm/agent/http/core/client.py
- tests/test_agent/test_http_core_client.py
This change improves on some validation of the incoming request and also does a bit of reorganization of `request()`.  This change is in preparation for another change which will implement the new http client functionality needed for inlineCallbacks.
> Improved HTTP Client Setup and Validation

- pyfarm/agent/http/core/client.py
- tests/test_agent/test_http_core_client.py
This change adds support to use the treq client as directly as possible and is a continuation of #206 (which should merge first).  This change is also a prerequisite for the inlineCallback work that's being done in other branches but we should be able to merge this without breaking the agent as it stands now.
> Direct HTTP Client (treq) Request Support

- pyfarm/agent/service.py
- tests/test_agent/test_service.py
Right now setting `shutting_down` on the agent will not necessarily communicate to other parts of the project, such as job types or other code which does not have easy access to the agent instance, that the agent is shutting down.  This change fixes this by turning `shutting_down` into a property that will return a result from the config when `self.shutting_down` is requested and set the value in the config with `self.shutting_down = <value>`
> Synchronize Agent.shutting_down with the config

- pyfarm/agent/service.py
- pyfarm/agent/testutil.py
- tests/test_agent/test_service.py
Similar to other recent branches the focus of this change is to convert a part of `service.py` to use inlineCallbacks.  In this case, the part which is performing a POST request to register the agent with the master.
> Convert post_agent_to_master to inlineCallbacks

- pyfarm/agent/utility.py
- pyfarm/jobtypes/core/log.py
- tests/test_agent/test_utility.py
- tests/test_jobtypes/test_core_log.py
This also removes the indirection via in-memory file objects for writing
CSVs and the encoding feature for the csv output. This feature was never
actually used anywhere, and the resulting behaviour not relied upon.
Keeping the indirection makes it impossible to fix this bug.
> Fix spurious newlines in CSVs in Windows

- pyfarm/agent/config.py
- pyfarm/agent/entrypoints/main.py
- pyfarm/agent/entrypoints/supervisor.py
- pyfarm/agent/http/api/state.py
- pyfarm/agent/service.py
- pyfarm/agent/sysinfo/system.py
- pyfarm/agent/utility.py
- pyfarm/jobtypes/core/internals.py
- tests/test_agent/test_utility.py
While looking around to figure out the next best code to transition to inlineCallbacks I found it would be easier to do a little cleanup first.  In this case I'm migrating calls to `os.remove` to a utility function which will file removal in a consistent manner while also offering some extra options.  The goal here is to provide a little cleanup while also not changing the intended behavior of the code being replaced.
This could also be used by job type implementors to handle file removal without having to write a bunch of wrapper code.
> Remove File Utility

- pyfarm/agent/service.py
- pyfarm/agent/testutil.py
- tests/test_agent/test_service.py
This change converts post_shutdown_to_master to inlineCallbacks.  In addition this change also fixes a couple of bugs regarding the shutdown timeout.
> Convert post_shutdown_to_master to inlineCallbacks

- pyfarm/agent/http/api/assign.py
- pyfarm/agent/service.py
Also, change it back to online when no assignment is being worked on
anymore.
As a side effect, this will cause the free_ram value to be updated
immediately after the last active assignment has stopped running,
which is probably the most interesting point in time for getting a
free_ram update anyway.
> Update the agent state to running when necessary

- tests/test_agent/test_utility.py
This change removes the mocks for logging in the tests for `remove_file()`.  They don't provide a great deal of benefit right and only complicate the test code.
> Remove Logging Mocks In remove_fie Tests

- tests/test_agent/test_service.py
There's no such thing as `assert_never_called()`, use `self.assertFalse(<thing>.called)` instead.
> Fix assertion in service test

- .coveragerc
- pyfarm/agent/utility.py
- tests/test_agent/test_utility.py
This PR does three things:
* Adds some missing tests for `pyfarm.agent.utility`
* Ensures that we also handle `WindowsError` when dealing with files
* Adds missing coverage exclusion for `logger.errror`
> More test coverage for pyfarm.agent.utility

- pyfarm/agent/entrypoints/supervisor.py
- pyfarm/agent/testutil.py
- pyfarm/agent/utility.py
- pyfarm/jobtypes/core/internals.py
- tests/test_agent/test_utility.py
This is a complimentary function to `utility.remove_file()`.  Adding this for use in tests mainly but also for job type implementors too.
> remove_directory utility

- pyfarm/agent/http/api/assign.py
Previously, the agent would erroneously leave its state on running if an
assignment stop with a failure.
> Bugfix: Set agent state on failed assignment, too

- pyfarm/agent/http/api/assign.py
- pyfarm/jobtypes/core/internals.py
This avoids a situation where the log has not been closed yet and might
still be written to while being uploaded.
As a side effect, _upload_logfile() now no longer takes a log
identifier, since an assignment is only supposed to have one log anyway.
> Upload logs after the assignment has finished

- pyfarm/agent/service.py
- pyfarm/agent/utility.py
- tests/test_agent/test_service.py
- tests/test_agent/test_utility.py
As the title says, this pull request converts `reannounce()` to use `@inlineCallbacks.`
> Convert reannounce to inlineCallbacks

- pyfarm/jobtypes/core/internals.py
- pyfarm/jobtypes/core/jobtype.py
JobType.is_successful() is user-overridable, so we have to assume it
might raise an exception.
The previous code would fail to call the stopped deferred is that
happened, resulting in the agent hanging.
> Catch exceptions from JobType.is_successful()

- pyfarm/jobtypes/core/internals.py
- tests/test_jobtypes/test_core_internals.py
These is a non-functional change that makes some small improvements to the `TypeChecks` class.  The main change is switching to `@staticmethod` since we don't need access to either the class or the instance.  This change also removes some tests which are no longer valid or are already covered by other tests.
> TypeChecks Cleanup/Improvements

- tests/test_agent/test_http_api_state.py
`TestStatus` has been somewhat unreliable and has caused failures in the past when we get unexpected results.  This change mocks out `memory.free_ram()` and `time.time()` so they return constant values.   In this particular test we don't care that those values are accurate we just care that they meet our expected results.  This change also properly cleans up the config in between test runs.
> Improve test_http_api_state.TestStatus

- pyfarm/agent/config.py
This change changes all logging calls in the config object to debug to cut down on logging output.  Full comment from 7709711506affb0e2f8fc02155168d2efa79d3c0:
```
The agent's configuration logger is probably
one of the most verbose loggers.  Its output
is important but probably only in cases where
there's a problem being debugged.  Even then the
configuration is usually not going to be the cause
of the issue so keeping the configuration logger
in debug only mode probably makes more sense.
```
> Change Config Logging to Debug

- pyfarm/agent/config.py
- pyfarm/agent/etc/agent.yml
- pyfarm/agent/logger/twistd.py
- pyfarm/agent/testutil.py
This change adds the `agent_global_logger_level` configuration variable.  The main purpose of this variable is to provide some control over the global logging level.  
The only side effect that I know of with this change is we'll miss a few debug level messages from just prior to the config loading because the default level is now INFO in `twistd.py`.  This is probably fixable with a couple of work arounds but I don't think we're going to be missing much because the config module is almost always one of the first modules to load.
> Configuration Based Logger Level

- pyfarm/agent/etc/agent.yml
- pyfarm/agent/testutil.py
The main points behind this PR are included in commit 7da7052b2075df19d8646c8152508249b5330dd4's comment.
* removing the DNS hostname check, we should just
let the request fail instead
* Move the url check into setUp() so it's not
performed at startup
* If the configuration does not define a url, don't
run the tests that require the url
* Set a timeout on the socket so we don't sit there forever
> Improve testutil setUp

- pyfarm/agent/testutil.py
- tests/test_agent/test_service.py
Simple noop change which just changes the default retry delay and gets rid of a couple of TODOs in the process.  This shaves 15-30 seconds off the test execution.
> Test Speedup

- pyfarm/agent/logger/twistd.py
Found this bug while working on #251, figured it should be split into its own review.
> Don't let improper log formatting raise exceptions

- setup.py
This PR is aimed at improving the information we're displaying to someone who is trying to install the agent on Windows.  This was opened in response to 
https://groups.google.com/a/pyfarm.net/forum/#!msg/discuss/PH6YkHV860U/4aYcXpULXP0J
> Improve error message in setup.py for Windows

- pyfarm/agent/service.py
- pyfarm/jobtypes/core/internals.py
- tests/test_jobtypes/test_core_internals.py
If we set the state of tasks not just on the task itself, but also on the current tasklog, we must make sure the tasklog is registered before we do that, otherwise that will fail with a 404.
In extreme cases, where assignments finish very fast, even uploading the final tasklog file at the end may fail because of this. (This can happen in practice if a jobtype class decides that no process needs to be started.)
Unfortunately, this PR still has a problem: When setting our agent's state, the request fails with this message:
2015-04-07 17:36:57 INFO     - pf.jobtypes.core - Spawning Command(command='/usr/bin/blender', arguments=('-b', '/home/guido/stift_aniex43_finish.blend', '-s', '196.0', '-e', '200.0', '-o', '/tmp/stift_####.exr', '-a'), cwd='/home/guido/git/pyfarm', user=None, group=None, …
> Register logfile before starting assignment

- pyfarm/agent/utility.py
Deleting files and directories is a normal part of operations.  There is
no reason to log that at log level info
> Log file and directory deletions at level DEBUG

- pyfarm/agent/http/api/assign.py
- pyfarm/jobtypes/core/internals.py
Merging #263 ended up breaking handling exceptions the jobtype's start()
method.  This should fix it again.
> Fix handling errors from jobtypes when starting

- pyfarm/jobtypes/core/jobtype.py
If we are shutting down, the task most likely has not actually failed,
and the child process(es) was/were killed because of the shutdown.  This
should not count towards the failure count of the current tasks.
> Refuse to set tasks to failed if shutting down

- pyfarm/agent/entrypoints/main.py
On Windows, when running as a non-privileged user, we sometimes fail to
start up if our pid file is stale, and the pid has since been taken by
another process running under some other user. This should fix that.
> Catch AccessDenied when checking pid on startup

- pyfarm/agent/http/api/assign.py
- pyfarm/jobtypes/core/jobtype.py
If we don't do this, the agent will sometimes reannounce itself with an
empty tasks list before all the tasks have been set to done/failed,
leading the master to believe the assignment has failed.
> Remove assignment only after all state updates

- pyfarm/agent/http/api/assign.py
- tests/test_agent/test_http_api_assign.py
Accepting assignments during a running reannounce can lead to weird
race, where the reannounce request is locally started right before the
incoming assignment, and uses data from that point in time, but doesn't
actually reach the master until after the incoming assignment. At that
point, the master has already marked the tasks as sent to agent and will
assume we failed it because our announce is lacking those task ids.
> Reject assignments if we are busy reannouncing

- pyfarm/agent/http/api/assign.py
This status code fits the situation better. After all, it isn't the client's fault, and technically there was nothing wrong with the request, we just cannot service it at the moment.
> Set status to SERVICE UNAVAILABLE for reannounce

- pyfarm/jobtypes/core/jobtype.py
This way, the master will see what state we think the assignment is in
when polling the agent.
> Remember local state for all tasks in assignment

- pyfarm/agent/http/core/resource.py
- pyfarm/agent/testutil.py
- tests/test_agent/test_http_core_resource.py
If the return value from a resource was either a string or a two part tuple the default content type header
was not being set.   The return value from `get_content_type()` was also incorrect (should be a list so setRawHeaders() can use it).  There were also cases where the code could be set incorrectly if both the rendering function and the base resource try to set the code.
> Missing Content-Type or Bad Codes In Some API Responses

- pyfarm/jobtypes/core/jobtype.py
This will fail if either of them contain non-ASCII characters.
> Don't convert jobtype name, job title to str

- .travis.yml
I'm going to phase out the pyfarm repository since it's not providing any value right now.  Before doing that however we need to change where we source retry.sh from.
> Use retry.sh from pyfarm-build

- pyfarm/agent/http/system.py
psutil 3.0 removed psutil.get_users() in favor of psutil.users().
> Fix getting logged in users with newer psutil

- pyfarm/agent/http/core/resource.py
Twisted-web is quite adamant about not wanting to write unicode objects.
> Fix creating error page

- pyfarm/jobtypes/core/log.py
Found this bug while working on #303.  On the Windows side it ends up raising an exception without this but on other platforms this does not seem to have been a problem so far.
Here's the error from Windows:
```
2015-08-25 02:23:29 INFO     - pf.jobtypes.log - Logging thread pool is shutting down.
2015-08-25 02:23:29 ERROR    - root            - Unhandled Error
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\twisted\trial\runner.py", line 981, in <lambda>
run = lambda: suite.run(result)
File "C:\Python27\lib\site-packages\twisted\trial\runner.py", line 235, in run
self._bail()
File "C:\Python27\lib\site-packages\twisted\trial\runner.py", line 224, in _bail
reactor.fireSystemEvent('shutdown') # radix's suggestion
File …
```
> Don't run stop() if we've never started or have joined a LoggerPool instance.

- pyfarm/agent/sysinfo/disks.py
From a comment in the code explaining this:
```
Not all disks can return disk information.  A partition
that is mounted but does not have a file system, cdrom
drives on Windows for example, wouldn't have any usage
data to return.
```
Found this problem on Windows while working on #303.
> disks.disks() should ignore OSError

- pyfarm/jobtypes/core/log.py
This PR cleans up the internals of flush some and also ensures that we handle `WindowsError` when it's available.  Found most of these improvements while working #303, figured they could be broken out.
> Cleanup log.py some and improve Windows handling

- pyfarm/agent/service.py
- pyfarm/agent/sysinfo/disks.py
- tests/test_agent/test_service.py
- tests/test_agent/test_sysinfo.py
Since we're catching OSError inside of disks.disks() we shouldn't need the bare try/except clause anymore.  This PR also adds the tests for disks.disks() and provides a `as_dict` keyword so we can skip the extra for loop in service.py
> Improve Usage of disks.disks()

- setup.py
Comment on ea11331 should explain most of the reasoning behind this.  I decided to remove the warning after seeing that on Windows this warning is usually shown to a user several times.  Additionally you can't really tell which package the warning came from which is misleading and could lead someone to believe something is wrong when there probably isn't.
> Remove warning about PyOpenSSL in setup.py on Windows

- pyfarm/agent/testutil.py
For comparison, here's the new output: https://travis-ci.org/pyfarm/pyfarm-agent/jobs/77930978
And here's the old output: https://travis-ci.org/pyfarm/pyfarm-agent/jobs/77850694
There's still a couple of places we're emitting output, but those will not be as easy to capture because of the context in which the logger is being used.
> Capture Logging/Silence tests in setUp

- pyfarm/jobtypes/core/log.py
The log emissions in this change should be DEBUG rather than
INFO.  Either a jobtype would be logging the file path, the
information we're logging is not useful outside of debug/testing or
there are other way we'd find out there's a problem (such as an
exception being raised).
> Lower some of the logging calls in core/log.py to DEBUG

- tests/test_jobtypes/test_core_process.py
This is a minor enhancement to test_core_process.py to use inlineCallbacks.  The test flow is more linear and has fewer indirect calls to the test functions.
This PR also improves on the internals of TestStopProcess too.
> Convert test_core_process to use @inlineCallbacks

- .gitignore
- README.rst
- appveyor.yml
- pyfarm/agent/sysinfo/disks.py
- pyfarm/agent/testutil.py
- pyfarm/jobtypes/core/log.py
- tests/test_agent/test_service.py
- tests/test_agent/test_sysinfo.py
- tests/test_jobtypes/test_core_internals.py
- tests/test_jobtypes/test_core_process.py
This PR bring Windows testing to pyfarm's agent via the Appveyor service.  Just like the Travis tests the CI service will be used to sign-off on a PR.  This PR also has the changes necessary to get the tests passing on Windows.
> Windows Testing With Appveyor

- .travis.yml
- README.rst
- pyfarm/agent/testutil.py
- tests/test_agent/test_http_api_state.py
- tests/test_jobtypes/test_core_internals.py
This PR removes the requirement to run the master in order for all tests to pass.  #303 also benefits from this because it will normalize test execution on Travis and Appveyor.
> Remove dependency on pyfarm-master from unittests

- pyfarm/agent/http/api/state.py
The previous code could get the agent stuck in an endless loop, because
the code that checks whether the agent should restart comes before the
code that removes the jobtype from config
> Don't delay restart for a non-running assignment

- pyfarm/agent/service.py
- tests/test_agent/test_service.py
This PR was created to simplify some of the tests for Agent.post_shutdown_to_master.  Mostly it removes many of the mocks and adds some additional output to post_shutdown_to_master that we can use when testing.  This also improves on a few tests that we inconsistently passing while working on #303.
> Improve Agent.post_shutdown_to_master tests.

- pyfarm/agent/http/api/state.py
jobtypes was misspelled and the endpoint would fail when there was no
"jobtypes" in config yet.
> Fix restart API endpoint

- tests/test_jobtypes/test_core_internals.py
This particular test has been a source of many of our recent failures, this PR should fix that.
From the commit message body:
```
Depending on the operating system, state of the disk
and other factors it's more reliable to check how many
files we cleaned up rather than explicit list.  In the real
world, we care more about the quantity/size anyway rather
than specific file names.
```
> Make test_cleans_up_disk_space() more reliable

- pyfarm/agent/sysinfo/software.py
- tests/test_agent/test_sysinfo.py
As the title says, this PR is improving on the coverage for `sysinfo.software`.  Original coverage is captured here: https://coveralls.io/builds/3655258/source?filename=pyfarm%2Fagent%2Fsysinfo%2Fsoftware.py
> Full test coverage for sysinfo.software

- tests/test_agent/test_sysinfo.py
This test assumed there's always more than one interface which
may not always be the case.  For example you've shutoff all network
adapters you should be left with one interface alone.  This of course
assumes all hosts have at least the loopback interface.
> Fix test_sysinfo.TestNetwork.test_interfaces test

- pyfarm/agent/http/api/assign.py
- tests/test_agent/test_http_api_assign.py
So while working on #334 it's become more apparent that in order to handle exceptions properly and generally cleanup the assignment APIs we need to do a little work converting it to inlineCallbacks.  Otherwise we can end up with a response going back to a client before a job type is actually loaded causing exceptions to possibly swallowed.
The modification of the assignment API to use inlineCallbacks will be broken down into another CL but for now this PR modifies some of the code from this style of response:
```python
request.setResponseCode(ACCEPTED)
request.write(dumps({"id": assignment_uuid}))
request.finish()
return NOT_DONE_YET
```
to:
```python
return dumps({"id": assignment_uuid}), ACCEPTED
```
This approach is cleaner and tightens the coupling some between the request being made …
> Modify assign API to respond directly with tuples

- pyfarm/jobtypes/core/log.py
KeyError can be raised if you don't call open_log() first.  This
error when running the tests is common for example.  open_log()
is usually called when the job type is started but if you're
writing tests or manually using the log pool the error message
could be more helpful.
> Reraise KeyError in LoggerPool.log with a better error message

- pyfarm/jobtypes/core/jobtype.py
Like most calls to os.makedirs, we should catch IOError and WindowsError too as they can crop up from time to time.
> JobType.tempdir() should handle IOError and WindowsError too

- pyfarm/jobtypes/core/jobtype.py
This PR improves the logic we had which was doing a type check on the inputs to `get_csvlog_path`.  Before we could have thrown an AssertionError when we probably meant to be throwing TypeError instead via `_check_csvlog_path_inputs()`.
> Fix/Improve JobType.get_csvlog_path()
