pyfarm/agent/entrypoints/main.py
This is a simple pull request to fix the rendering of the pid in a log message when the agent starts up.
=> Fix logged pid in startup

pyfarm/agent/service.py
This fixes a bug introduced in #192.  It's my fault for not catching this in the review though #145 probably would have caught this (my IDE noticed it when I tried merging the master into my working branch).  Sorry about that...
=> Sigint handler fix

pyfarm/jobtypes/core/internals.py
This change improves on _remove_directories() inside internals.py a little by:
* Using one thread to cleanup multiple directories
* Only making one attempt to remove a directory, instead of several in a very short period of time, before scheduling a retry on exit.
=> Improved _remove_directories()

pyfarm/jobtypes/core/internals.py
To be used by jobtype implementors
=> Implement utility method for cleaning up temp dirs

pyfarm/jobtypes/core/internals.py
A few minor fixes to the tempdir cleanup code.
=> Tempdir cleanup fixes

pyfarm/agent/entrypoints/main.py, pyfarm/agent/http/templates/assign.html, pyfarm/agent/service.py
This mirrors a change on the master.
=> Remove project column in agent model

pyfarm/agent/service.py
As discussed in #218 and #219 this change removes the code which POSTs CPU and RAM values to the master.  This code is currently unused and is being removed in favor os the reannouce functionality.
=> Remove CPU/RAM Update Methods

tests/test_agent/test_entrypoints_utility.py, tests/test_agent/test_testutil.py
There are some tests for testutil which are currently in the wrong location, this PR fixes that.
=> Fix testutil test location

tests/test_agent/test_service.py
`system_data()` was missing a few lines of coverage, this PR fixes that.
=> Improved coverage for system_data()

tests/test_agent/test_service.py
This PR adds tests for the agent's `build_http_resource()` method.
=> Tests for build_http_resource()

pyfarm/agent/utility.py
"str" objects will be left as they are.
Fixes #246
=> Encode only unicode objects to UTF-8

pyfarm/jobtypes/core/log.py, tests/test_jobtypes/test_core_log.py
Simplifies LoggerPool.flush() a bit.  Now only one thread will ever
write messages to the log file at a time, until it is finished.
Before, if there were several threads writing (which can happen if a lot
of output is produced in a short time), the lock would constantly pass
from one thread to the next, and as long as messages keep coming in, no
thread will ever actually finish.
Also, now the log file is unconditionally flushed every time a thread
ends.  This is better for jobtypes that produce little output in case an
admin wants to find out how far a running assignment has gotten (or why
it is stuck).
=> Rework how LoggerPool.flush() writes to disk

pyfarm/jobtypes/core/internals.py, tests/test_jobtypes/test_core_internals.py
This PR improves on the tests for `jobtype.core.internals` and will provide a couple bugfixes as well.
=> jobtype.core.internals basic test improvements and bugfixes

pyfarm/agent/service.py
By posting the state update before stopping running assignments, we
avoid having the master assign us new work in the narrow window
in-between, and then failing it when polling us the next time.
=> Move posting shutdown forward in stop sequence

pyfarm/jobtypes/core/internals.py
This fixes two bugs:
- The error callback was called with the wrong number of arguments.
- On retrying, this method would generate a new deferred and forget
about the old one.
=> Fix deferred handling in register logfile method

pyfarm/agent/etc/agent.yml, pyfarm/agent/http/core/client.py, pyfarm/agent/service.py, pyfarm/jobtypes/core/internals.py
Workaround for https://twistedmatrix.com/trac/ticket/7843
=> Retry reannounce request if connection was dropped

pyfarm/agent/http/api/tasklogs.py, pyfarm/agent/testutil.py, tests/test_agent/test_http_api_tasklogs.py
This change adds full coverage for the /tasklogs/ endpoint and also fixes a couple of latent bugs.
=> Bugfixes and Tests for /tasklogs/

pyfarm/agent/http/api/assign.py, pyfarm/jobtypes/core/internals.py, pyfarm/jobtypes/core/jobtype.py
and substitute some more readable ones.
=> Reduce severity of some log statements

pyfarm/agent/service.py, pyfarm/agent/sysinfo/disks.py, tests/test_agent/test_service.py
Warning: This needs an accompanying change in the master, otherwise there will be an incompatibility.
=> Send available disk space information to master

pyfarm/agent/http/api/assign.py, pyfarm/jobtypes/core/jobtype.py
When a task fails because we couldn't free enough disk space for it,
that doesn't mean there is anything inherently wrong with that task, it
only mean that task cannot be run on this node at this point in time.
If we only set the tasks state to queued and dissociate it with this
agent, however, there is a high likelihood that the master's scheduler
will just immediately reassign that task to us.  To avoid that, we add
this agent to the failed_on_agents list of that task.
=> Do not treat insufficient temp space as failure

pyfarm/jobtypes/core/jobtype.py
We were using the wrong url and data variables
=> Fix updating tasklogs

pyfarm/jobtypes/core/internals.py
We are having problems with render nodes whose temp directories are filling up. This should offer a way to mitigate those problems.
=> Add method in JobType to clean up system temp dir

pyfarm/jobtypes/core/jobtype.py
This PR simplifies the logic inside of get_uid_gid() by:
* Removing the extra construction of a list
* Removing the unnecessary calls to all()
* Reworking the if statement a bit so it's faster
=> Simplify JobType.get_uid_gid() logic

pyfarm/jobtypes/core/jobtype.py
This is more of an internal improvement on the documentation and variable naming.  There are not any functional changes here.
=> Improve JobType.get_command_list()
